/**
 * Bridge – Configuration (publisher only)
 * Set these once before distributing to users. End users do not edit this file.
 */

const CONFIG = {
  SPOTIFY_CLIENT_ID: 'YOUR_SPOTIFY_CLIENT_ID',

  GOOGLE_CLIENT_ID: 'YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com',

  FIREBASE: {
    apiKey: 'YOUR_FIREBASE_API_KEY',
    authDomain: 'YOUR_PROJECT.firebaseapp.com',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT.appspot.com',
    messagingSenderId: 'YOUR_SENDER_ID',
    appId: 'YOUR_APP_ID'
  }
};

// Export for use in modules (loaded as script in popup/background)
if (typeof window !== 'undefined') {
  window.BRIDGE_CONFIG = CONFIG;
}
